import streamlit as st

st.title("Methodology")

st.markdown(
    """
    <style>
    h1 a, h2 a {
        display: none !important;
    }
    </style>
    """, unsafe_allow_html=True,
)

st.markdown("""
## Pipeline

```
SPICE deck generation  →  parallel ngspice simulation  →  delay/power
extraction  →  pooled dataset  →  structural feature engineering  →
Random Forest training  →  CLI / interactive app
```

**SPICE characterization.** Each gate type (inverter, NAND2, NOR2, XOR2)
has a parameterized sky130 SPICE template. 500 samples per gate are
generated by randomizing supply voltage, temperature, transistor widths,
and load capacitance across physically reasonable ranges, then simulated
with `ngspice` against the real sky130 `tt`-corner BSIM4 device models.

**Direction-aware delay extraction.** Every switching input is a
`PULSE` waveform with both a rising and falling edge inside one
simulation run, so both propagation directions are measured from a
single transient: `tpHL` (output high-to-low) and `tpLH` (output
low-to-high). These are defined by the **output's** actual direction,
not assumed from the input's direction -- this matters because some
gate configurations are non-inverting (e.g. XOR2 with its static input
held at 0, where the output tracks the switching input directly).
`delay_ps` is reported as the worst-case of the two, matching standard
cell-library timing convention.

**Structural feature engineering.** Different gate types have different
transistor counts and different raw width columns (`width_p1` means a
different physical device in NAND2 vs. NOR2 vs. XOR2), so raw widths
aren't directly comparable across gate types. Instead, every row is
converted to gate-agnostic structural features: `pmos_series_depth` /
`nmos_series_depth` (how many transistors are stacked in series along
that network -- a fixed topology property), and `total_pmos_width` /
`total_nmos_width` (summed device width, a proxy for drive strength).
""")

st.markdown("""
## Key finding: series-stack delay penalty

Once trained, the models' feature importances put `gate_type` itself
near the *bottom* of the ranking -- once the model knows a row's
series-stack depth and total device widths, it barely needs to know
which specific gate type the row belongs to. That's because the
engineered structural features already encode nearly all the
information gate identity would provide: they're a physically
meaningful stand-in for "why do gates differ," rather than the model
memorizing a per-gate lookup.

This matches the underlying circuit physics directly: NOR2's
pull-**up** network is a series-PMOS stack (the slower device type,
due to lower hole mobility in sky130), which shows up as a sharp
`tpLH` >> `tpHL` asymmetry -- visible in the Dataset Explorer's
tpHL-vs-tpLH tab, where NOR2's points sit well above the diagonal
while NAND2's cluster much closer to it.
""")

st.markdown("""
## Known limitations

- **Widths are intentionally not optimally sized.** Real standard-cell
  libraries size stacked transistors to compensate for series
  resistance (a fixed, engineered choice per cell). This dataset
  instead randomizes each width independently across a broad range,
  including "badly sized" configurations -- deliberate, so the trained
  model learns a genuine width → delay/power relationship rather than
  seeing width as a constant.
- **XOR2's local inverters share one width** (`width_inv`) across all
  four of their transistors, rather than independently sized PMOS/NMOS
  -- a simplification, not physically ideal sizing.
- **Only the `tt` (typical-typical) process corner** is characterized;
  no `ff`/`ss` corner data.
""")